### create recipe
POST http://localhost:3000/recipe/
Content-Type: application/json

{
   "name": "pasta",
   "ingredient": "tomato sauce",
   "instruction": "sautee"
  
}

### fetch user
GET http://localhost:3000/recipe/pizza