### create recipe
POST http://localhost:3000/recipe/
Content-Type: application/json

{
   "name": "pizza",
   "ingredient": "flour",
   "instruction": "mix"
  
}

### fetch user
GET http://localhost:3000/recipe/pizza